language: objective-c
osx_image: xcode11

script: xcodebuild clean build test -project DizzyKit.xcodeproj -scheme DizzyKit -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0' CODE_SIGNING_REQUIRED=NO
